export const ACTIONS = {
	SET_FIELDS: 'SET_FIELDS',
	UPDATE_SLUG: 'UPDATE_SLUG',
	CLEAR_STOCK: 'CLEAR_STOCK',
	SET_ERRORS: 'SET_ERRORS',
	CREATE_SUCCESS: 'CREATE_SUCCESS',
	EDIT_SUCCESS: 'EDIT_SUCCESS',
}
