<?php 

	/*Adding Custom Blocks to ACF*/
	if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_606e40dd83bb9',
		'title' => 'Custom Blocks',
		'fields' => array(
			array(
				'key' => 'field_606e40dd8a71c',
				'label' => 'Custom Blocks',
				'name' => 'custom_blocks',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_5cd1c10bae148' => array(
						'key' => 'layout_5cd1c10bae148',
						'name' => 'custom_blocks_one_column',
						'label' => 'One Column',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_606e40dd8df51',
								'label' => 'Full Screen One Column',
								'name' => 'custom_blocks_one_column_full_screen',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606e40dd8df55',
								'label' => 'Vertical Alignment',
								'name' => 'custom_blocks_one_column_vertical_alignment',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'align-top' => 'Top',
									'align-middle' => 'Middle',
									'align-bottom' => 'Bottom',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'align-middle',
								'layout' => 'vertical',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_606e40dd8df6c',
								'label' => 'Block height - small screen',
								'name' => 'custom_blocks_one_column_block_height_small_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8df51',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8df71',
								'label' => 'Block height - medium screen',
								'name' => 'custom_blocks_one_column_block_height_medium_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8df51',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8df76',
								'label' => 'Block height - large screen',
								'name' => 'custom_blocks_one_column_block_height_large_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8df51',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8df7a',
								'label' => 'Background Color',
								'name' => 'custom_blocks_one_column_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array(
								'key' => 'field_606e40dd8df7f',
								'label' => 'Background Image',
								'name' => 'custom_blocks_one_column_background_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_609c3143d9695',
								'label' => 'Hide image on mobile',
								'name' => 'custom_blocks_one_column_display_image_on_mobile',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606e40dd8df84',
								'label' => 'Video Type',
								'name' => 'custom_blocks_one_column_video_type',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'none' => 'None',
									'youtube' => 'YouTube',
									'vimeo' => 'Vimeo',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_606e40dd8df88',
								'label' => 'Video ID',
								'name' => 'custom_blocks_one_column_video_id',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8df84',
											'operator' => '!=',
											'value' => 'none',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_606e40dd8df8d',
								'label' => 'Font Color',
								'name' => 'custom_blocks_one_column_font_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array(
								'key' => 'field_606e40dd8df92',
								'label' => 'Content',
								'name' => 'custom_blocks_one_column_content',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5cd1c1c5f1edb' => array(
						'key' => 'layout_5cd1c1c5f1edb',
						'name' => 'custom_blocks_two_columns',
						'label' => 'Two Columns',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_60957a8d0b2ac',
								'label' => 'Animation',
								'name' => 'custom_blocks_two_columns_animation',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606e40dd8df97',
								'label' => 'Full Screen Two Columns',
								'name' => 'custom_blocks_two_columns_full_screen',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606e40dd8df9b',
								'label' => 'Vertical Alignment',
								'name' => 'custom_blocks_two_columns_vertical_alignment',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'align-top' => 'Top',
									'align-middle' => 'Middle',
									'align-bottom' => 'Bottom',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'align-middle',
								'layout' => 'vertical',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_606e40dd8dfa0',
								'label' => 'Block height - small screen',
								'name' => 'custom_blocks_two_columns_block_height_small_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8df97',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8dfa4',
								'label' => 'Block height - medium screen',
								'name' => 'custom_blocks_two_columns_block_height_medium_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8df97',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8dfa9',
								'label' => 'Block height - large screen',
								'name' => 'custom_blocks_two_columns_block_height_large_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8df97',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8dfae',
								'label' => 'Background Color',
								'name' => 'custom_blocks_two_columns_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array(
								'key' => 'field_606e40dd8dfb2',
								'label' => 'Background Image',
								'name' => 'custom_blocks_two_column_background_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_609c31e9d9696',
								'label' => 'Hide image on mobile',
								'name' => 'custom_blocks_two_columns_display_image_on_mobile',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606e40dd8dfb7',
								'label' => 'Video Type.',
								'name' => 'custom_blocks_two_column_video_type',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'none' => 'None',
									'youtube' => 'YouTube',
									'vimeo' => 'Vimeo',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_606e40dd8dfbc',
								'label' => 'Video ID',
								'name' => 'custom_blocks_two_column_video_id',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8dfb7',
											'operator' => '!=',
											'value' => 'none',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_606e40dd8dfc1',
								'label' => 'Font Color',
								'name' => 'custom_blocks_two_columns_font_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array(
								'key' => 'field_606e40dd8dfc5',
								'label' => 'Mobile Order Content Left',
								'name' => 'custom_blocks_two_columns_content_left_order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 1,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8dfca',
								'label' => 'Content Left',
								'name' => 'custom_blocks_two_columns_content_left',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_606e40dd8dfce',
								'label' => 'Mobile Order Content Right',
								'name' => 'custom_blocks_two_columns_content_right_order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 1,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8dfd3',
								'label' => 'Content Right',
								'name' => 'custom_blocks_two_columns_content_right',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_606f15d8a85c4' => array(
						'key' => 'layout_606f15d8a85c4',
						'name' => 'custom_blocks_two_columns_with_numeration',
						'label' => 'Two Columns With Numeration',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_606f15d8a85c5',
								'label' => 'Full Screen Two Columns With Numeration',
								'name' => 'custom_blocks_two_columns_full_screen_with_numeration',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606f15d8a85c6',
								'label' => 'Vertical Alignment',
								'name' => 'custom_blocks_two_columns_vertical_alignment_with_numeration',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'align-top' => 'Top',
									'align-middle' => 'Middle',
									'align-bottom' => 'Bottom',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'align-middle',
								'layout' => 'vertical',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_606f15d8a85ca',
								'label' => 'Background Color',
								'name' => 'custom_blocks_two_columns_background_color_with_numeration',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array(
								'key' => 'field_606f15d8a85cb',
								'label' => 'Background Image',
								'name' => 'custom_blocks_two_column_background_image_with_numeration',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_609c3241d9697',
								'label' => 'Hide image on mobile',
								'name' => 'custom_blocks_two_columns_with_numeration_display_image_on_mobile',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606f15d8a85cc',
								'label' => 'Video Type.',
								'name' => 'custom_blocks_two_column_video_type_with_numeration',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'none' => 'None',
									'youtube' => 'YouTube',
									'vimeo' => 'Vimeo',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_606f15d8a85cd',
								'label' => 'Video ID',
								'name' => 'custom_blocks_two_column_video_id_with_numeration',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606f15d8a85cc',
											'operator' => '!=',
											'value' => 'none',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_606f15d8a85ce',
								'label' => 'Font Color',
								'name' => 'custom_blocks_two_columns_font_color_with_numeration',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array(
								'key' => 'field_6070a37d42576',
								'label' => 'Title',
								'name' => 'custom_blocks_two_columns_title_with_numeration',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_606f15d8a85d0',
								'label' => 'Content Left',
								'name' => 'custom_blocks_two_columns_content_left_with_numeration',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_606f15d8a85d4',
								'label' => 'Content Right',
								'name' => 'custom_blocks_two_columns_content_right_with_numeration',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_606f2ee784cb0',
										'label' => 'Box text',
										'name' => 'custom_blocks_two_columns_content_right_box_with_numeration',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'visual',
										'toolbar' => 'medium',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5d712921e4c66' => array(
						'key' => 'layout_5d712921e4c66',
						'name' => 'custom_blocks_three_columns',
						'label' => 'Three Columns',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_606e40dd8dfd8',
								'label' => 'Full Screen Three Columns',
								'name' => 'custom_blocks_three_columns_full_screen',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606e40dd8dfdd',
								'label' => 'Vertical Alignment',
								'name' => 'custom_blocks_three_columns_vertical_alignment',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'align-top' => 'Top',
									'align-middle' => 'Middle',
									'align-bottom' => 'Bottom',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'align-middle',
								'layout' => 'vertical',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_606e40dd8dfe1',
								'label' => 'Block height - small screen',
								'name' => 'custom_blocks_three_columns_block_height_small_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8dfd8',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8dfe6',
								'label' => 'Block height - medium screen',
								'name' => 'custom_blocks_three_columns_block_height_medium_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8dfd8',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8dfeb',
								'label' => 'Block height - large screen',
								'name' => 'custom_blocks_three_columns_block_height_large_screen',
								'type' => 'number',
								'instructions' => 'When field is blank or equals 0, height will be auto-set.',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8dfd8',
											'operator' => '!=',
											'value' => '1',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 0,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8dfef',
								'label' => 'Background Color',
								'name' => 'custom_blocks_three_columns_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array(
								'key' => 'field_606e40dd8dff4',
								'label' => 'Background Image',
								'name' => 'custom_blocks_three_column_background_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_609c326bd9698',
								'label' => 'Hide image on mobile',
								'name' => 'custom_blocks_three_columns_display_image_on_mobile',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606e40dd8dff9',
								'label' => 'Video Type.',
								'name' => 'custom_blocks_three_column_video_type',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'none' => 'None',
									'youtube' => 'YouTube',
									'vimeo' => 'Vimeo',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_606e40dd8dffd',
								'label' => 'Video ID',
								'name' => 'custom_blocks_three_column_video_id',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_606e40dd8dff9',
											'operator' => '!=',
											'value' => 'none',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_606e40dd8e002',
								'label' => 'Font Color',
								'name' => 'custom_blocks_three_columns_font_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array(
								'key' => 'field_606e40dd8e007',
								'label' => 'Mobile Order Content Left',
								'name' => 'custom_blocks_three_columns_content_left_order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 1,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8e00b',
								'label' => 'Content Left',
								'name' => 'custom_blocks_three_columns_content_left',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_606e40dd8e010',
								'label' => 'Mobile Order Content Center',
								'name' => 'custom_blocks_three_columns_content_center_order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 1,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8e014',
								'label' => 'Content Center',
								'name' => 'custom_blocks_three_columns_content_center',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_606e40dd8e019',
								'label' => 'Mobile Order Content Right',
								'name' => 'custom_blocks_three_columns_content_right_order',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => 1,
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_606e40dd8e01e',
								'label' => 'Content Right',
								'name' => 'custom_blocks_three_columns_content_right',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_6074aa2a8f862' => array(
						'key' => 'layout_6074aa2a8f862',
						'name' => 'simple_content',
						'label' => 'Simple Content',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6074aa2a8f863',
								'label' => 'Full Screen One Column',
								'name' => 'simple_content_full_screen',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_6074aa2a8f868',
								'label' => 'Background Color',
								'name' => 'simple_content_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array(
								'key' => 'field_6074aa2a8f869',
								'label' => 'Background Image',
								'name' => 'simple_content_background_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_609c329bd9699',
								'label' => 'Hide image on mobile',
								'name' => 'simple_content_display_image_on_mobile',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_6074aa2a8f86c',
								'label' => 'Font Color',
								'name' => 'simple_content_font_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array(
								'key' => 'field_6074aa2a8f86d',
								'label' => 'Content',
								'name' => 'simple_content_column_content',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_606f2ffb76784' => array(
						'key' => 'layout_606f2ffb76784',
						'name' => 'custom_blocks_quotes',
						'label' => 'Quotes',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_606f2ffb76785',
								'label' => 'Full Screen Quotes',
								'name' => 'custom_blocks_quotes',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606f2ffb76786',
								'label' => 'Vertical Alignment',
								'name' => 'custom_blocks_quotes_vertical_alignment',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'align-top' => 'Top',
									'align-middle' => 'Middle',
									'align-bottom' => 'Bottom',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'align-middle',
								'layout' => '',
								'return_format' => '',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_606f2ffb76787',
								'label' => 'Background Color',
								'name' => 'custom_blocks_quotes_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array(
								'key' => 'field_606f2ffb76788',
								'label' => 'Background Image',
								'name' => 'custom_blocks_quotes_background_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => '',
								'preview_size' => 'medium',
								'library' => '',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_609c32dad969a',
								'label' => 'Hide image on mobile',
								'name' => 'custom_blocks_quotes_display_image_on_mobile',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606f2ffb7678b',
								'label' => 'Font Color',
								'name' => 'custom_blocks_quotes_font_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array(
								'key' => 'field_606f30567678f',
								'label' => 'Title',
								'name' => 'custom_blocks_quotes_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_606f307076790',
								'label' => 'Description',
								'name' => 'custom_blocks_quotes_description',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'medium',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_606f30e576791',
								'label' => 'Quote',
								'name' => 'custom_blocks_quotes_quote',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_606f30fb76792',
										'label' => 'Image',
										'name' => 'custom_blocks_quotes_quote_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_606f316276793',
										'label' => 'Name',
										'name' => 'custom_blocks_quotes_quote_name',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_606f317176794',
										'label' => 'Label',
										'name' => 'custom_blocks_quotes_quote_label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_606f318d76795',
										'label' => 'Body copy',
										'name' => 'custom_blocks_quotes_quote_body_copy',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'medium',
										'media_upload' => 1,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_60958046c7444' => array(
						'key' => 'layout_60958046c7444',
						'name' => 'custom_blocks_cards_quotes',
						'label' => 'Cards Quotes',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_60958046c7445',
								'label' => 'Full Screen Quotes',
								'name' => 'custom_blocks_cards_quotes_full',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_60958046c7446',
								'label' => 'Vertical Alignment',
								'name' => 'custom_blocks_cards_quotes_vertical_alignment',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'align-top' => 'Top',
									'align-middle' => 'Middle',
									'align-bottom' => 'Bottom',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'align-middle',
								'layout' => 'vertical',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_60958046c7447',
								'label' => 'Background Color',
								'name' => 'custom_blocks_cards_quotes_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#ffffff',
							),
							array(
								'key' => 'field_60958046c7448',
								'label' => 'Background Image',
								'name' => 'custom_blocks_cards_quotes_background_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_609c330ad969b',
								'label' => 'Hide image on mobile',
								'name' => 'custom_blocks_cards_quotes_display_image_on_mobile',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_60958046c7449',
								'label' => 'Font Color',
								'name' => 'custom_blocks_cards_quotes_font_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '#000000',
							),
							array(
								'key' => 'field_60958046c744a',
								'label' => 'Title',
								'name' => 'custom_blocks_cards_quotes_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_60958105c7451',
								'label' => 'Cards',
								'name' => 'custom_blocks_cards_quotes_cards',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_609581f0c7452',
										'label' => 'Image',
										'name' => 'custom_blocks_cards_quotes_cards_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_6095821bc7453',
										'label' => 'Content',
										'name' => 'custom_blocks_cards_quotes_cards_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'medium',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_609d65b2130f1',
										'label' => 'Show quote icon',
										'name' => 'custom_blocks_cards_quotes_cards_show_quote_icon',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 1,
										'ui' => 0,
										'ui_on_text' => '',
										'ui_off_text' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_6070eec5adf5e' => array(
						'key' => 'layout_6070eec5adf5e',
						'name' => 'custom_blocks_external_posts',
						'label' => 'External Posts',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_607484ae12e5d',
								'label' => 'Title',
								'name' => 'custom_blocks_archive_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_6070eeddadf5f',
								'label' => 'Post',
								'name' => 'custom_blocks_external_posts_post',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_6089e58c76cb0',
										'label' => 'Image',
										'name' => 'custom_blocks_external_posts_post_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_6089e5b776cb1',
										'label' => 'Title',
										'name' => 'custom_blocks_external_posts_post_title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_6089e5e476cb2',
										'label' => 'Content',
										'name' => 'custom_blocks_external_posts_post_content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_6089e5ff76cb3',
										'label' => 'Button',
										'name' => 'custom_blocks_external_posts_post_button',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_606f349d76796' => array(
						'key' => 'layout_606f349d76796',
						'name' => 'custom_blocks_video',
						'label' => 'Video',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6080620b80588',
								'label' => 'Background Color',
								'name' => 'custom_blocks_video_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_60806768de3b3',
								'label' => 'Font Color',
								'name' => 'custom_blocks_video_font_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_60806750de3b2',
								'label' => 'Title',
								'name' => 'custom_blocks_video_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_6080622d80589',
								'label' => 'Margin',
								'name' => 'custom_blocks_video_margin',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_606f349d76797',
								'label' => 'Video ID',
								'name' => 'custom_blocks_video_id',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_607df6838dc6c' => array(
						'key' => 'layout_607df6838dc6c',
						'name' => 'custom_blocks_images_width_link',
						'label' => 'Images with link',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_607df7e5f69b2',
								'label' => 'Background Color',
								'name' => 'custom_blocks_images_width_link_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_607df804f69b3',
								'label' => 'Background Image',
								'name' => 'custom_blocks_images_width_link_background_image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => '1536x1536',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_609c3337d969c',
								'label' => 'Hide image on mobile',
								'name' => 'custom_blocks_images_width_link_display_image_on_mobile',
								'type' => 'true_false',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'message' => '',
								'default_value' => 0,
								'ui' => 0,
								'ui_on_text' => '',
								'ui_off_text' => '',
							),
							array(
								'key' => 'field_607df6838dc6d',
								'label' => 'Images',
								'name' => 'custom_blocks_images_width_link_repeater',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_607df6b58dc6e',
										'label' => 'Image',
										'name' => 'custom_blocks_images_width_link_image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_607df6cd8dc6f',
										'label' => 'Link',
										'name' => 'custom_blocks_images_width_link_link',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_6095a342ab8d6' => array(
						'key' => 'layout_6095a342ab8d6',
						'name' => 'custom_blocks_separator',
						'label' => 'Separator',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_6095a342ab8d7',
								'label' => 'Background Color',
								'name' => 'custom_blocks_separator_background_color',
								'type' => 'color_picker',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
							),
							array(
								'key' => 'field_6095a342ab8d9',
								'label' => 'Height',
								'name' => 'custom_blocks_separator_height',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Block',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_template',
					'operator' => '==',
					'value' => 'template-full-custom.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => true,
		'description' => '',
	));

	endif;